#!/bin/bash
#
# Sets up "Send to ImageOptim" in one go: installs the command, installs the
# Finder Quick Action that calls it, refreshes the Services cache, and checks
# that ImageOptim actually accepts the handoff.
#
# Generated by tools/build-setup.py -- edit src/send-to-imageoptim.sh instead.
#
#     ./setup.sh              install
#     ./setup.sh --uninstall  remove everything it installed

set -euo pipefail

name="Send to ImageOptim"
bin_dir="$HOME/.local/bin"
command_path="$bin_dir/send-to-imageoptim"
bundle="$HOME/Library/Services/$name.workflow"

if [ "$(uname -s)" != "Darwin" ]; then
    echo "This is a macOS Finder service; it only installs on macOS." >&2
    exit 1
fi

if [ "${1:-}" = "--uninstall" ]; then
    rm -rf "$bundle" && echo "Removed $bundle"
    rm -f "$command_path" && echo "Removed $command_path"
    [ -x /System/Library/CoreServices/pbs ] && /System/Library/CoreServices/pbs -flush >/dev/null 2>&1 || true
    exit 0
fi

# --- the command ------------------------------------------------------------
mkdir -p "$bin_dir"
cat >"$command_path" <<'SEND_TO_IMAGEOPTIM_SCRIPT'
#!/bin/bash
#
# send-to-imageoptim -- hand a set of files (or folders) to ImageOptim.app
#
# ImageOptim has no real CLI, so the files are handed over the same way a
# drag-and-drop does: an "open documents" Apple Event sent straight to the app.
# `open -a ImageOptim file.png` looks like the obvious way to do it, but it
# goes through LaunchServices, which refuses with "ImageOptim cannot open
# files in the PNG image format" on builds whose bundle does not advertise
# those document types. A drop never consults that list, and neither does the
# Apple Event. Two cruder fallbacks follow it; see handoff() below.
#
# This script is the body of the "Send to ImageOptim" Finder Quick Action and
# also works standalone:  send-to-imageoptim ~/Pictures/*.png
#
# Configuration (environment variables):
#   IMAGEOPTIM_EXTS  space-separated list of extensions to accept
#                    (default: png jpg jpeg gif svg)
#   IMAGEOPTIM_APP   full path to the .app bundle (default: located with
#                    Spotlight, then /Applications and ~/Applications)
#   IMAGEOPTIM_QUIET set to 1 to suppress the "nothing to do" notification
#   IMAGEOPTIM_METHOD pin the handoff: applescript | applescript_name |
#                    launchargs | openapp
#                    (default: try them in that order, keep the first that
#                    works)
#
# The same three can be set in ~/.config/send-to-imageoptim/config, which is
# sourced as shell -- handy for tuning the installed Quick Action without
# rebuilding it, e.g.  IMAGEOPTIM_EXTS="png jpg jpeg"

set -u

# Environment wins over the config file, which wins over these defaults.
env_exts=${IMAGEOPTIM_EXTS:-}
env_app=${IMAGEOPTIM_APP:-}
env_quiet=${IMAGEOPTIM_QUIET:-}
env_method=${IMAGEOPTIM_METHOD:-}

config=${XDG_CONFIG_HOME:-$HOME/.config}/send-to-imageoptim/config
# shellcheck source=/dev/null
[ -r "$config" ] && . "$config"

exts=${env_exts:-${IMAGEOPTIM_EXTS:-"png jpg jpeg gif svg"}}
quiet=${env_quiet:-${IMAGEOPTIM_QUIET:-0}}
method=${env_method:-${IMAGEOPTIM_METHOD:-}}

notify() {
    # $1 = message, $2 = title
    /usr/bin/osascript -e "display notification $(quote_as "$1") with title $(quote_as "${2:-ImageOptim}")" >/dev/null 2>&1 || true
}

quote_as() {
    # AppleScript string literal
    local s=${1//\\/\\\\}
    printf '"%s"' "${s//\"/\\\"}"
}

die() {
    printf 'send-to-imageoptim: %s\n' "$1" >&2
    notify "$1" "ImageOptim"
    exit 1
}

usage() {
    cat <<'USAGE'
usage: send-to-imageoptim [file|folder ...]
       send-to-imageoptim --check

Adds the given images to ImageOptim's queue. Folders are passed through
whole; ImageOptim walks them recursively. Files whose extension is not in
IMAGEOPTIM_EXTS (default: png jpg jpeg gif svg) are skipped.

--check reports which ImageOptim it found and sends it a test image it
creates itself, printing which handoff method the app accepted. Whether the
app then actually opened it is something only looking at ImageOptim tells you.
USAGE
}

do_check=0
case ${1:-} in
    -h|--help) usage; exit 0 ;;
    --check)   do_check=1 ;;
esac

if [ "$do_check" -eq 0 ] && [ $# -eq 0 ]; then
    usage >&2
    exit 2
fi

# --- locate ImageOptim ------------------------------------------------------
app=${env_app:-${IMAGEOPTIM_APP:-}}
if [ -z "$app" ]; then
    # By name, through LaunchServices: it knows where the app actually is, and
    # unlike a hardcoded bundle ID it cannot be wrong about which build this is.
    app=$(/usr/bin/osascript -e 'POSIX path of (path to application "ImageOptim")' 2>/dev/null) || app=""
fi
if [ -z "$app" ]; then
    app=$(/usr/bin/mdfind "kMDItemFSName == 'ImageOptim.app'" 2>/dev/null | /usr/bin/head -n 1)
fi
if [ -z "$app" ]; then
    for candidate in /Applications/ImageOptim.app "$HOME/Applications/ImageOptim.app"; do
        [ -d "$candidate" ] && { app=$candidate; break; }
    done
fi
[ -z "$app" ] && die "ImageOptim is not installed. Get it at https://imageoptim.com"
app=${app%/}

# The real identifiers, read off the bundle we actually found.
bundle_id=$(/usr/bin/defaults read "$app/Contents/Info" CFBundleIdentifier 2>/dev/null) || bundle_id=""
app_name=${app##*/}
app_name=${app_name%.app}

# --- hand off ---------------------------------------------------------------
# What a drop does: an open-documents Apple Event to the running (or
# newly launched) app. No LaunchServices document-type check, no second copy.
applescript_open() {
    # $1 is a complete AppleScript application specifier
    local specifier=$1
    shift
    /usr/bin/osascript - "$@" >/dev/null 2>&1 <<APPLESCRIPT
on run argv
    set theFiles to {}
    repeat with thePath in argv
        set end of theFiles to POSIX file (thePath as text)
    end repeat
    tell application $specifier
        activate
        open theFiles
    end tell
end run
APPLESCRIPT
}

handoff_applescript() {
    [ -n "$bundle_id" ] || return 1
    applescript_open "id \"$bundle_id\"" "$@"
}

# Same event, addressed by name -- the fallback for when the bundle carries an
# identifier LaunchServices has not registered.
handoff_applescript_name() {
    applescript_open "\"$app_name\"" "$@"
}

# ImageOptim also reads paths out of its own argv, but --args is only
# delivered to a process being launched, hence the new instance.
handoff_launchargs() {
    /usr/bin/open -n -a "$app" --args "$@" >/dev/null 2>&1
}

# The obvious one, kept last: LaunchServices may refuse the file types.
handoff_openapp() {
    /usr/bin/open -a "$app" "$@" >/dev/null 2>&1
}

METHODS="applescript applescript_name launchargs openapp"

handoff() {
    case $method in
        applescript|applescript_name|launchargs|openapp)
            "handoff_$method" "$@"; return $? ;;
    esac
    local candidate
    for candidate in $METHODS; do
        if "handoff_$candidate" "$@"; then
            method=$candidate   # stick with whatever worked for later batches
            return 0
        fi
    done
    return 1
}


# --- self test --------------------------------------------------------------
# A 1x1 PNG, so --check needs no file from the caller and cannot fail over a
# path that turns out not to exist.
TEST_PNG=iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==

selftest() {
    local dir file candidate
    printf 'App       : %s\n' "$app"
    printf 'Bundle ID : %s\n' "${bundle_id:-(none in Info.plist)}"
    if [ "$bundle_id" != "net.pornel.ImageOptim" ]; then
        printf '\nNote: that is not imageoptim.com'"'"'s ImageOptim (net.pornel.ImageOptim).\n'
        printf 'Other apps ship under the same name. At least one of them declares no\n'
        printf 'document types and takes files by drag-and-drop only -- it will accept the\n'
        printf 'handoff below and then refuse the file with a dialog of its own.\n\n'
    fi

    dir=$(/usr/bin/mktemp -d "${TMPDIR:-/tmp}/send-to-imageoptim.XXXXXXXX") || return 1
    file=$dir/send-to-imageoptim-test.png
    printf '%s' "$TEST_PNG" | /usr/bin/base64 -D >"$file" 2>/dev/null ||
        printf '%s' "$TEST_PNG" | /usr/bin/base64 --decode >"$file"
    [ -s "$file" ] || { printf 'could not write a test image\n' >&2; return 1; }
    printf 'Test image: %s\n\n' "$file"

    for candidate in $METHODS; do
        printf '  %-18s' "$candidate"
        if "handoff_$candidate" "$file"; then
            printf ' accepted\n'
            # Accepted means the app took the event without complaint. It does
            # not prove the app opened the file -- only looking does.
            printf '\nNow look at ImageOptim: it should be showing send-to-imageoptim-test.png.\n'
            printf 'If it is, everything works. If it is not, or it put up an error, the app\n'
            printf 'took the handoff and ignored the file, and no method here will fix that.\n'
            printf '\nTo pin this method: IMAGEOPTIM_METHOD=%s in\n' "$candidate"
            printf '~/.config/send-to-imageoptim/config\n'
            return 0
        fi
        printf ' refused\n'
    done

    printf '\nNothing worked. Send the output above back to whoever asked for it.\n' >&2
    return 1
}

if [ "$do_check" -eq 1 ]; then
    selftest
    exit $?
fi

# --- filter the selection ---------------------------------------------------
matches_ext() {
    local name=${1##*/}
    local ext=${name##*.}
    [ "$ext" = "$name" ] && return 1          # no extension at all
    ext=$(printf '%s' "$ext" | /usr/bin/tr '[:upper:]' '[:lower:]')
    local candidate
    for candidate in $exts; do
        [ "$ext" = "$candidate" ] && return 0
    done
    return 1
}

sent=0
skipped=0
files=()

for path in "$@"; do
    # Always hand `open` an absolute path: Finder gives us those anyway, and it
    # keeps a name that starts with "-" from being read as an option.
    case $path in
        /*) ;;
         *) path=$PWD/$path ;;
    esac
    if [ -e "$path" ] && { [ -d "$path" ] || matches_ext "$path"; }; then
        files+=("$path")
        sent=$((sent + 1))
    else
        skipped=$((skipped + 1))
    fi
done

if [ "$sent" -eq 0 ]; then
    if [ "$quiet" != "1" ]; then
        if [ "$skipped" -eq 1 ]; then
            notify "That file is not one ImageOptim can optimize." "ImageOptim"
        else
            notify "None of those $skipped items are files ImageOptim can optimize." "ImageOptim"
        fi
    fi
    exit 0
fi

# Send in batches so a selection of thousands cannot blow past ARG_MAX.
batch=200
index=0
while [ "$index" -lt "$sent" ]; do
    handoff "${files[@]:index:batch}" || die "ImageOptim would not accept the files."
    index=$((index + batch))
done

exit 0
SEND_TO_IMAGEOPTIM_SCRIPT
chmod +x "$command_path"
echo "Installed $command_path"

# --- the Quick Action -------------------------------------------------------
rm -rf "$bundle"
mkdir -p "$bundle/Contents"
cat >"$bundle/Contents/Info.plist" <<'SEND_TO_IMAGEOPTIM_INFO'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSServices</key>
	<array>
		<dict>
			<key>NSMenuItem</key>
			<dict>
				<key>default</key>
				<string>Send to ImageOptim</string>
			</dict>
			<key>NSMessage</key>
			<string>runWorkflowAsService</string>
			<key>NSRequiredContext</key>
			<dict>
				<key>NSApplicationIdentifier</key>
				<string>com.apple.finder</string>
			</dict>
			<key>NSSendFileTypes</key>
			<array>
				<string>public.image</string>
				<string>public.folder</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
SEND_TO_IMAGEOPTIM_INFO
cat >"$bundle/Contents/document.wflow" <<'SEND_TO_IMAGEOPTIM_WFLOW'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AMApplicationBuild</key>
	<string>521</string>
	<key>AMApplicationVersion</key>
	<string>2.10</string>
	<key>AMDocumentVersion</key>
	<string>2</string>
	<key>actions</key>
	<array>
		<dict>
			<key>action</key>
			<dict>
				<key>AMAccepts</key>
				<dict>
					<key>Container</key>
					<string>List</string>
					<key>Optional</key>
					<true/>
					<key>Types</key>
					<array>
						<string>com.apple.cocoa.string</string>
					</array>
				</dict>
				<key>AMActionVersion</key>
				<string>2.0.3</string>
				<key>AMApplication</key>
				<array>
					<string>Automator</string>
				</array>
				<key>AMParameterProperties</key>
				<dict>
					<key>COMMAND_STRING</key>
					<dict/>
					<key>CheckedForUserDefaultShell</key>
					<dict/>
					<key>inputMethod</key>
					<dict/>
					<key>shell</key>
					<dict/>
					<key>source</key>
					<dict/>
				</dict>
				<key>AMProvides</key>
				<dict>
					<key>Container</key>
					<string>List</string>
					<key>Types</key>
					<array>
						<string>com.apple.cocoa.string</string>
					</array>
				</dict>
				<key>ActionBundlePath</key>
				<string>/System/Library/Automator/Run Shell Script.action</string>
				<key>ActionName</key>
				<string>Run Shell Script</string>
				<key>ActionParameters</key>
				<dict>
					<key>COMMAND_STRING</key>
					<string>exec "$HOME/.local/bin/send-to-imageoptim" "$@"
</string>
					<key>CheckedForUserDefaultShell</key>
					<true/>
					<key>inputMethod</key>
					<integer>1</integer>
					<key>shell</key>
					<string>/bin/bash</string>
					<key>source</key>
					<string></string>
				</dict>
				<key>BundleIdentifier</key>
				<string>com.apple.RunShellScript</string>
				<key>CFBundleVersion</key>
				<string>2.0.3</string>
				<key>CanShowSelectedItemsWhenRun</key>
				<false/>
				<key>CanShowWhenRun</key>
				<true/>
				<key>Category</key>
				<array>
					<string>AMCategoryUtilities</string>
				</array>
				<key>Class Name</key>
				<string>RunShellScriptAction</string>
				<key>InputUUID</key>
				<string>7A0C2D14-8E39-4F51-A6B2-0C9D8E7F6A51</string>
				<key>Keywords</key>
				<array>
					<string>Shell</string>
					<string>Script</string>
					<string>Command</string>
					<string>Run</string>
					<string>Unix</string>
				</array>
				<key>OutputUUID</key>
				<string>C4B39E27-5A18-4D63-8F0E-2B7A1C6D9E42</string>
				<key>UUID</key>
				<string>3E1F5B0A-4C6D-4E2A-9B77-1D2C3F4A5B60</string>
				<key>UnlocalizedApplications</key>
				<array>
					<string>Automator</string>
				</array>
				<key>arguments</key>
				<dict>
					<key>0</key>
					<dict>
						<key>default value</key>
						<integer>0</integer>
						<key>name</key>
						<string>inputMethod</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>0</string>
					</dict>
					<key>1</key>
					<dict>
						<key>default value</key>
						<string></string>
						<key>name</key>
						<string>source</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>1</string>
					</dict>
					<key>2</key>
					<dict>
						<key>default value</key>
						<false/>
						<key>name</key>
						<string>CheckedForUserDefaultShell</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>2</string>
					</dict>
					<key>3</key>
					<dict>
						<key>default value</key>
						<string></string>
						<key>name</key>
						<string>COMMAND_STRING</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>3</string>
					</dict>
					<key>4</key>
					<dict>
						<key>default value</key>
						<string>/bin/sh</string>
						<key>name</key>
						<string>shell</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>4</string>
					</dict>
				</dict>
				<key>isViewVisible</key>
				<integer>1</integer>
				<key>location</key>
				<string>309.000000:253.000000</string>
				<key>nibPath</key>
				<string>/System/Library/Automator/Run Shell Script.action/Contents/Resources/Base.lproj/main.nib</string>
			</dict>
			<key>isViewVisible</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>connectors</key>
	<dict/>
	<key>workflowMetaData</key>
	<dict>
		<key>applicationBundleIDsByPath</key>
		<dict>
			<key>/System/Library/CoreServices/Finder.app</key>
			<string>com.apple.finder</string>
		</dict>
		<key>applicationPaths</key>
		<array>
			<string>/System/Library/CoreServices/Finder.app</string>
		</array>
		<key>inputTypeIdentifier</key>
		<string>com.apple.Automator.fileSystemObject</string>
		<key>outputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>presentationMode</key>
		<integer>11</integer>
		<key>processesInput</key>
		<integer>0</integer>
		<key>serviceApplicationBundleID</key>
		<string>com.apple.finder</string>
		<key>serviceApplicationPath</key>
		<string>/System/Library/CoreServices/Finder.app</string>
		<key>serviceInputTypeIdentifier</key>
		<string>com.apple.Automator.fileSystemObject</string>
		<key>serviceOutputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>serviceProcessesInput</key>
		<integer>0</integer>
		<key>systemImageName</key>
		<string>NSActionTemplate</string>
		<key>useAutomaticInputType</key>
		<integer>0</integer>
		<key>workflowTypeIdentifier</key>
		<string>com.apple.Automator.servicesMenu</string>
	</dict>
</dict>
</plist>
SEND_TO_IMAGEOPTIM_WFLOW
echo "Installed $bundle"

[ -x /System/Library/CoreServices/pbs ] && /System/Library/CoreServices/pbs -flush >/dev/null 2>&1 || true
killall Finder >/dev/null 2>&1 || true

# --- does the handoff actually work? ----------------------------------------
echo
if "$command_path" --check; then
    cat <<'DONE'

Finder: select some images, right-click, Quick Actions > Send to ImageOptim.

Not there? Open System Settings > Keyboard > Keyboard Shortcuts > Services,
expand "Files and Folders", and tick "Send to ImageOptim". That is also where
you can give it a keyboard shortcut.
DONE
else
    cat <<'FAILED'

The Quick Action is installed, but ImageOptim would not take the test image.
The lines above show which methods were tried; send them on.
FAILED
    exit 1
fi
