// Generated by tools/make_golden.py -- do not edit by hand.
//
// scipy designs these once, here, and the app only runs them. Every
// frequency below is a constant in the Python, so nothing is lost by
// fixing them at build time, and a Butterworth prototype, a frequency
// transform, a bilinear transform and a pole-zero pairing all stop
// being things that could be ported wrongly.
//
// Change a corner frequency in the Python and re-run the generator.

import Foundation

public enum FilterBank {
    public static let rate = 48000.0

    /// Butterworth order 4, band, 31.5 to 63 Hz.
    public static let subBand = SOS([
        [1.7969644940387247e-11, 3.5939289880774495e-11, 1.7969644940387247e-11, 1.0, -1.9956156539984855, 0.9956607726150207],
        [1.0, 2.0, 1.0, 1.0, -1.9967095261726113, 0.9967350559245856],
        [1.0, -2.0, 1.0, 1.0, -1.9978656821391865, 0.997930579909048],
        [1.0, -2.0, 1.0, 1.0, -1.9988985016869179, 0.9989162901789991],
    ])

    /// Butterworth order 4, band, 30 to 100 Hz.
    public static let kickBand = SOS([
        [4.353509107668849e-10, 8.707018215337698e-10, 4.353509107668849e-10, 1.0, -1.98909415981225, 0.9891859194906301],
        [1.0, 2.0, 1.0, 1.0, -1.993931592427604, 0.9939601471144637],
        [1.0, -2.0, 1.0, 1.0, -1.9945343750187914, 0.9946953292518961],
        [1.0, -2.0, 1.0, 1.0, -1.9982908945822357, 0.9983072539943698],
    ])

    /// Butterworth order 4, band, 2000 to 6000 Hz.
    public static let punchBand = SOS([
        [0.002576434425322622, 0.005152868850645244, 0.002576434425322622, 1.0, -1.2725770520987314, 0.5362133261119552],
        [1.0, 2.0, 1.0, 1.0, -1.5828025192022797, 0.6863787247026745],
        [1.0, -2.0, 1.0, 1.0, -1.2668845173541454, 0.7556000599766302],
        [1.0, -2.0, 1.0, 1.0, -1.829766715372079, 0.8983316617647493],
    ])

    /// Butterworth order 2, high, 28 Hz.
    public static let subFloor = SOS([
        [0.9974116737880857, -1.9948233475761714, 0.9974116737880857, 1.0, -1.9948166481323713, 0.994830047019971],
    ])

    /// Butterworth order 4, low, 75 Hz.
    public static let subCeiling = SOS([
        [5.732218814633091e-10, 1.1464437629266182e-09, 5.732218814633091e-10, 1.0, -1.9819274951072672, 0.9820230108587963],
        [1.0, 2.0, 1.0, 1.0, -1.9924182510631434, 0.9925142723994841],
    ])

    /// Butterworth order 2, low, 20 Hz.
    public static let envelope20 = SOS([
        [1.7103058908949044e-06, 3.420611781789809e-06, 1.7103058908949044e-06, 1.0, -1.996297601769122, 0.9963044429926857],
    ])

    /// Butterworth order 2, low, 200 Hz.
    public static let envelope200 = SOS([
        [0.00016822370859146955, 0.0003364474171829391, 0.00016822370859146955, 1.0, -1.9629800893893397, 0.9636529842237055],
    ])

    /// Butterworth order 2, low, 200 Hz.
    public static let onsetFast = SOS([
        [0.00016822370859146955, 0.0003364474171829391, 0.00016822370859146955, 1.0, -1.9629800893893397, 0.9636529842237055],
    ])

}