#!/usr/bin/env python3
"""Generate setup.sh -- a single self-contained installer.

Same idea as tools/build-workflow.py: the one true copy of the logic is
src/send-to-imageoptim.sh, and everything shippable is generated from it, so
nothing can drift. setup.sh writes the command to ~/.local/bin, writes a Quick
Action that calls it, refreshes the Services cache and runs the self test.

    python3 tools/build-setup.py
"""

import importlib.util
import plistlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "src" / "send-to-imageoptim.sh"
OUT = ROOT / "setup.sh"

spec = importlib.util.spec_from_file_location("bw", Path(__file__).parent / "build-workflow.py")
bw = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bw)

# The bundle setup.sh writes calls the installed command rather than carrying
# its own copy of it, so there is only ever one script on disk to update.
COMMAND = 'exec "$HOME/.local/bin/send-to-imageoptim" "$@"\n'

TEMPLATE = """#!/bin/bash
#
# Sets up "Send to ImageOptim" in one go: installs the command, installs the
# Finder Quick Action that calls it, refreshes the Services cache, and checks
# that ImageOptim actually accepts the handoff.
#
# Generated by tools/build-setup.py -- edit src/send-to-imageoptim.sh instead.
#
#     ./setup.sh              install
#     ./setup.sh --uninstall  remove everything it installed

set -euo pipefail

name="Send to ImageOptim"
bin_dir="$HOME/.local/bin"
command_path="$bin_dir/send-to-imageoptim"
bundle="$HOME/Library/Services/$name.workflow"

if [ "$(uname -s)" != "Darwin" ]; then
    echo "This is a macOS Finder service; it only installs on macOS." >&2
    exit 1
fi

if [ "${{1:-}}" = "--uninstall" ]; then
    rm -rf "$bundle" && echo "Removed $bundle"
    rm -f "$command_path" && echo "Removed $command_path"
    [ -x /System/Library/CoreServices/pbs ] && /System/Library/CoreServices/pbs -flush >/dev/null 2>&1 || true
    exit 0
fi

# --- the command ------------------------------------------------------------
mkdir -p "$bin_dir"
cat >"$command_path" <<'SEND_TO_IMAGEOPTIM_SCRIPT'
{script}
SEND_TO_IMAGEOPTIM_SCRIPT
chmod +x "$command_path"
echo "Installed $command_path"

# --- the Quick Action -------------------------------------------------------
rm -rf "$bundle"
mkdir -p "$bundle/Contents"
cat >"$bundle/Contents/Info.plist" <<'SEND_TO_IMAGEOPTIM_INFO'
{info}
SEND_TO_IMAGEOPTIM_INFO
cat >"$bundle/Contents/document.wflow" <<'SEND_TO_IMAGEOPTIM_WFLOW'
{wflow}
SEND_TO_IMAGEOPTIM_WFLOW
echo "Installed $bundle"

[ -x /System/Library/CoreServices/pbs ] && /System/Library/CoreServices/pbs -flush >/dev/null 2>&1 || true
killall Finder >/dev/null 2>&1 || true

# --- does the handoff actually work? ----------------------------------------
echo
if "$command_path" --check; then
    cat <<'DONE'

Finder: select some images, right-click, Quick Actions > Send to ImageOptim.

Not there? Open System Settings > Keyboard > Keyboard Shortcuts > Services,
expand "Files and Folders", and tick "Send to ImageOptim". That is also where
you can give it a keyboard shortcut.
DONE
else
    cat <<'FAILED'

The Quick Action is installed, but ImageOptim would not take the test image.
The lines above show which methods were tried; send them on.
FAILED
    exit 1
fi
"""


def main() -> int:
    script = SCRIPT.read_text().rstrip("\n")
    info = plistlib.dumps(bw.info_plist()).decode().rstrip("\n")
    wflow = plistlib.dumps(bw.document_wflow(COMMAND)).decode().rstrip("\n")

    for name, blob in (("script", script), ("Info.plist", info), ("document.wflow", wflow)):
        for terminator in ("SEND_TO_IMAGEOPTIM_SCRIPT", "SEND_TO_IMAGEOPTIM_INFO",
                           "SEND_TO_IMAGEOPTIM_WFLOW"):
            if any(line.strip() == terminator for line in blob.splitlines()):
                print(f"{name} contains the heredoc terminator {terminator}", file=sys.stderr)
                return 1

    OUT.write_text(TEMPLATE.format(script=script, info=info, wflow=wflow))
    OUT.chmod(0o755)
    print(f"built {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
